services:
  AppBundle\Repository\LeagueRepository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\League

  AppBundle\Repository\TeamRepository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\Team

  AppBundle\Repository\UserRepository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\User